import type { KycProvider } from "./kyc.interface.js";

// ---------------------------------------------------------------------------
// Mock KycProvider — for dev and test environments.
// Simulates a Smile Identity check:
//   - startCheck: returns a deterministic ref immediately
//   - getStatus:  returns VERIFIED after a ref that starts with "mock_kyc_"
//                 (so tests can also assert FAILED by passing a different prefix)
// ---------------------------------------------------------------------------

export const mockKycProvider: KycProvider = {
  async startCheck(creatorId, _data) {
    return { ref: `mock_kyc_${creatorId}_${Date.now()}` };
  },

  async getStatus(ref) {
    // Refs generated by this mock always return VERIFIED.
    // To test the FAILED path, pass a ref that starts with "mock_kyc_fail_".
    if (ref.startsWith("mock_kyc_fail_")) return "FAILED";
    if (ref.startsWith("mock_kyc_")) return "VERIFIED";
    return "PROCESSING";
  },
};
