import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import { motion, AnimatePresence } from "motion/react";
import { ChevronLeft, ChevronDown, LifeBuoy, X, Send, Headset } from "lucide-react";
import { apiClient } from "../../lib/api-client";
import { formatRelativeTime } from "../../lib/utils";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Input } from "../components/ui/Input";
import { Modal } from "../components/ui/Modal";
import type { SupportTicket } from "@monologg/types";

const FAQS: Array<{ q: string; a: string }> = [
  {
    q: "When does a talent get paid?",
    a: "Once a client approves delivered work, funds release from escrow automatically. Payouts typically arrive within 24 business hours.",
  },
  {
    q: "What happens if I'm not satisfied with the delivery?",
    a: "You can dispute a booking before approving it. Disputes are reviewed and can result in a refund back to the client.",
  },
  {
    q: "How do I change my notification preferences?",
    a: "Go to Settings → Notifications to control which updates you receive.",
  },
  {
    q: "How is my identity verification different from AI style tags?",
    a: "They're fully independent. Identity verification (the Verified badge) comes from a dedicated ID check. Style tags are generated by analyzing your reel and never affect verification status.",
  },
];

const TICKET_STATUS_TONE: Record<SupportTicket["status"], "success" | "accent" | "neutral"> = {
  OPEN: "accent",
  IN_PROGRESS: "accent",
  RESOLVED: "success",
  CLOSED: "neutral",
};

export function HelpSupport() {
  const navigate = useNavigate();
  const [tickets, setTickets] = useState<SupportTicket[]>([]);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [selectedTicket, setSelectedTicket] = useState<SupportTicket | null>(null);
  const [chatMessages, setChatMessages] = useState<Array<{ id: string; sender: "user" | "agent"; text: string; time: string }>>([]);
  const [chatInput, setChatInput] = useState("");

  useEffect(() => {
    apiClient.listSupportTickets().then(setTickets);
  }, []);

  const openTicketChat = (ticket: SupportTicket) => {
    setSelectedTicket(ticket);
    setChatMessages([
      { id: "1", sender: "user", text: ticket.message || "I need assistance with my account/booking.", time: "Earlier" },
      { id: "2", sender: "agent", text: "Hello! Thank you for reaching out to Monologg Customer Care. Agent Sarah here — I am reviewing your request and will assist you right away.", time: "Just now" },
    ]);
  };

  const handleSendChatMessage = () => {
    if (!chatInput.trim()) return;
    const text = chatInput.trim();
    setChatInput("");
    setChatMessages(prev => [
      ...prev,
      { id: `c-${Date.now()}`, sender: "user", text, time: "Just now" }
    ]);
    setTimeout(() => {
      setChatMessages(prev => [
        ...prev,
        { id: `c-${Date.now() + 1}`, sender: "agent", text: "Got it! I am looking into this and updating your ticket notes.", time: "Just now" }
      ]);
    }, 1200);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject.trim() || !message.trim()) return;
    setSubmitting(true);
    try {
      const created = await apiClient.submitSupportTicket({ subject, message });
      setTickets((prev) => [
        created ?? {
          id: `local-${Date.now()}`,
          subject,
          message,
          status: "OPEN" as const,
          createdAt: new Date().toISOString(),
        },
        ...prev,
      ]);
      setSubject("");
      setMessage("");
      setSubmitted(true);
      setTimeout(() => setSubmitted(false), 2500);
    } finally {
      setSubmitting(false);
    }
  };

  const s = {
    text: { color: "var(--color-text-primary)" } as React.CSSProperties,
    secondary: { color: "var(--color-text-secondary)" } as React.CSSProperties,
    tertiary: { color: "var(--color-text-tertiary)" } as React.CSSProperties,
    surface: { background: "var(--color-bg-surface)", border: "1px solid var(--color-hairline)" } as React.CSSProperties,
  };

  return (
    <div className="min-h-screen flex flex-col" style={{ background: "var(--color-bg-canvas)" }}>
      <div className="h-16 flex items-center gap-3 px-4 sticky top-0 z-40 glass-panel" style={{ borderBottom: "1px solid var(--color-hairline)" }}>
        <button
          aria-label="Go back"
          onClick={() => navigate(-1)}
          className="w-10 h-10 rounded-[var(--radius-full)] flex items-center justify-center hover:opacity-80 active:scale-95 transition-all"
          style={{ background: "var(--color-bg-elevated)", color: "var(--color-text-secondary)" }}
        >
          <ChevronLeft className="w-5 h-5" />
        </button>
        <div className="text-sm font-semibold font-display" style={s.text}>Help &amp; Support</div>
      </div>

      <div className="flex-1 px-4 py-5 max-w-lg mx-auto w-full">
        <div className="text-xs font-medium uppercase tracking-wider mb-2 px-1 font-body" style={s.tertiary}>Frequently Asked Questions</div>
        <div className="rounded-[var(--radius-xl)] overflow-hidden mb-8" style={{ ...s.surface, boxShadow: "var(--shadow-card)" }}>
          {FAQS.map((item, i) => (
            <div key={item.q} style={{ borderBottom: i < FAQS.length - 1 ? "1px solid var(--color-hairline)" : undefined }}>
              <button
                className="w-full flex items-center justify-between gap-3 px-4 py-3.5 text-left"
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                aria-expanded={openFaq === i}
              >
                <span className="text-sm font-medium font-body" style={s.text}>{item.q}</span>
                <ChevronDown
                  className="w-4 h-4 shrink-0 transition-transform"
                  style={{ ...s.tertiary, transform: openFaq === i ? "rotate(180deg)" : undefined }}
                />
              </button>
              {openFaq === i && (
                <p className="px-4 pb-4 text-sm font-body leading-relaxed" style={s.secondary}>{item.a}</p>
              )}
            </div>
          ))}
        </div>

        <div className="text-xs font-medium uppercase tracking-wider mb-2 px-1 font-body" style={s.tertiary}>Contact Support</div>
        <form onSubmit={handleSubmit} className="rounded-[var(--radius-xl)] p-4 mb-8 space-y-3" style={{ ...s.surface, boxShadow: "var(--shadow-card)" }}>
          <Input placeholder="Subject" value={subject} onChange={(e) => setSubject(e.target.value)} required />
          <textarea
            placeholder="Describe your issue…"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            required
            rows={4}
            className="w-full rounded-[var(--radius-lg)] border px-3 py-2.5 font-body text-sm resize-none"
            style={{ ...s.surface, color: "var(--color-text-primary)" }}
          />
          <Button type="submit" className="w-full" disabled={submitting || !subject.trim() || !message.trim()}>
            {submitting ? "Sending…" : submitted ? "Sent!" : "Submit Request"}
          </Button>
        </form>

        <div className="text-xs font-medium uppercase tracking-wider mb-2 px-1 font-body" style={s.tertiary}>Your Requests</div>
        {tickets.length === 0 ? (
          <div className="flex flex-col items-center text-center py-10">
            <LifeBuoy className="w-8 h-8 mb-3" style={s.tertiary} />
            <p className="text-sm font-body" style={s.secondary}>No requests submitted yet.</p>
          </div>
        ) : (
          <div className="rounded-[var(--radius-xl)] overflow-hidden" style={{ ...s.surface, boxShadow: "var(--shadow-card)" }}>
            {tickets.map((ticket, i) => (
              <div
                key={ticket.id}
                onClick={() => openTicketChat(ticket)}
                className="px-4 py-3.5 cursor-pointer hover:bg-[var(--color-bg-elevated)] transition-colors"
                style={{ borderBottom: i < tickets.length - 1 ? "1px solid var(--color-hairline)" : undefined }}
              >
                <div className="flex items-center justify-between gap-2 mb-1">
                  <span className="text-sm font-semibold font-body truncate" style={s.text}>{ticket.subject}</span>
                  <Badge tone={TICKET_STATUS_TONE[ticket.status]}>{ticket.status.replace("_", " ")}</Badge>
                </div>
                <div className="text-xs font-body flex items-center justify-between" style={s.tertiary}>
                  <span>{formatRelativeTime(ticket.createdAt)}</span>
                  <span className="text-xs font-semibold hover:underline" style={{ color: "var(--color-accent)" }}>Chat with Agent →</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Support Agent Live Chat Modal */}
      <AnimatePresence>
        {selectedTicket && (
          <Modal onClose={() => setSelectedTicket(null)}>
            <motion.div
              initial={{ y: 20, scale: 0.95 }} animate={{ y: 0, scale: 1 }} exit={{ y: 20, scale: 0.95 }}
              className="w-full max-w-md rounded-[var(--radius-xl)] p-5 h-[80vh] flex flex-col"
              style={{ background: "var(--color-bg-surface)", border: "1px solid var(--color-hairline)", boxShadow: "var(--shadow-elevated)" }}
              onClick={e => e.stopPropagation()}
            >
              {/* Header */}
              <div className="flex items-center justify-between pb-3 border-b" style={{ borderColor: "var(--color-hairline)" }}>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full flex items-center justify-center" style={{ background: "var(--color-accent-glow)" }}>
                    <Headset className="w-5 h-5" style={{ color: "var(--color-accent)" }} />
                  </div>
                  <div>
                    <h3 className="font-display text-base font-semibold" style={{ color: "var(--color-text-primary)" }}>Customer Care Agent</h3>
                    <div className="text-xs font-body flex items-center gap-1.5" style={{ color: "var(--color-text-tertiary)" }}>
                      <span className="w-2 h-2 rounded-full" style={{ background: "var(--color-success)" }} /> Agent Sarah · Online
                    </div>
                  </div>
                </div>
                <button onClick={() => setSelectedTicket(null)} className="w-8 h-8 rounded-full flex items-center justify-center" style={{ background: "var(--color-bg-elevated)" }}>
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Ticket details banner */}
              <div className="p-3 my-3 rounded-[var(--radius-md)] flex items-center justify-between text-xs font-body" style={{ background: "var(--color-bg-elevated)" }}>
                <span className="font-medium truncate max-w-[200px]" style={{ color: "var(--color-text-secondary)" }}>{selectedTicket.subject}</span>
                <Badge tone={TICKET_STATUS_TONE[selectedTicket.status]} size="sm">{selectedTicket.status}</Badge>
              </div>

              {/* Chat messages */}
              <div className="flex-1 overflow-y-auto space-y-3 p-2">
                {chatMessages.map(msg => {
                  const isUser = msg.sender === "user";
                  return (
                    <div key={msg.id} className={`flex ${isUser ? "justify-end" : "justify-start"}`}>
                      <div
                        className="max-w-[80%] p-3 rounded-xl text-xs font-body"
                        style={{
                          background: isUser ? "var(--color-accent)" : "var(--color-bg-elevated)",
                          color: isUser ? "var(--color-accent-on)" : "var(--color-text-primary)",
                          border: isUser ? undefined : "1px solid var(--color-hairline)",
                        }}
                      >
                        <p>{msg.text}</p>
                        <div className="text-[10px] mt-1 opacity-70 text-right">{msg.time}</div>
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Chat input */}
              <div className="flex items-center gap-2 pt-3 border-t" style={{ borderColor: "var(--color-hairline)" }}>
                <Input
                  placeholder="Type a message to support agent…"
                  value={chatInput}
                  onChange={e => setChatInput(e.target.value)}
                  onKeyDown={e => e.key === "Enter" && handleSendChatMessage()}
                  className="flex-1 h-10 text-xs"
                />
                <Button className="h-10 w-10 p-0 flex items-center justify-center shrink-0" onClick={handleSendChatMessage} disabled={!chatInput.trim()}>
                  <Send className="w-4 h-4" />
                </Button>
              </div>
            </motion.div>
          </Modal>
        )}
      </AnimatePresence>
    </div>
  );
}

