import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import { ChevronLeft, ChevronDown, LifeBuoy } from "lucide-react";
import { apiClient } from "../../lib/api-client";
import { formatRelativeTime } from "../../lib/utils";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Input } from "../components/ui/Input";
import type { SupportTicket } from "@monologg/types";

// Static FAQ content (features.md Phase 10 explicitly allows "static or
// CMS-backed" — no CMS exists in any phase, so this is the honest choice,
// not a placeholder for one).
const FAQS: Array<{ q: string; a: string }> = [
  {
    q: "When does a talent get paid?",
    a: "Once a client approves delivered work, funds release from escrow automatically. Payouts typically arrive within 24 business hours.",
  },
  {
    q: "What happens if I'm not satisfied with the delivery?",
    a: "You can dispute a booking before approving it. Disputes are reviewed and can result in a refund back to the client.",
  },
  {
    q: "How do I change my notification preferences?",
    a: "Go to Settings → Notifications to control which updates you receive.",
  },
  {
    q: "How is my identity verification different from AI style tags?",
    a: "They're fully independent. Identity verification (the Verified badge) comes from a dedicated ID check. Style tags are generated by analyzing your reel and never affect verification status.",
  },
];

const TICKET_STATUS_TONE: Record<SupportTicket["status"], "success" | "accent" | "neutral"> = {
  OPEN: "accent",
  IN_PROGRESS: "accent",
  RESOLVED: "success",
  CLOSED: "neutral",
};

export function HelpSupport() {
  const navigate = useNavigate();
  const [tickets, setTickets] = useState<SupportTicket[]>([]);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    apiClient.listSupportTickets().then(setTickets);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject.trim() || !message.trim()) return;
    setSubmitting(true);
    try {
      const created = await apiClient.submitSupportTicket({ subject, message });
      setTickets((prev) => [
        created ?? {
          id: `local-${Date.now()}`,
          subject,
          message,
          status: "OPEN" as const,
          createdAt: new Date().toISOString(),
        },
        ...prev,
      ]);
      setSubject("");
      setMessage("");
      setSubmitted(true);
      setTimeout(() => setSubmitted(false), 2500);
    } finally {
      setSubmitting(false);
    }
  };

  const s = {
    text: { color: "var(--color-text-primary)" } as React.CSSProperties,
    secondary: { color: "var(--color-text-secondary)" } as React.CSSProperties,
    tertiary: { color: "var(--color-text-tertiary)" } as React.CSSProperties,
    surface: { background: "var(--color-bg-surface)", border: "1px solid var(--color-hairline)" } as React.CSSProperties,
  };

  return (
    <div className="min-h-screen flex flex-col" style={{ background: "var(--color-bg-canvas)" }}>
      <div className="h-16 flex items-center gap-3 px-4 sticky top-0 z-40 glass-panel" style={{ borderBottom: "1px solid var(--color-hairline)" }}>
        <button
          aria-label="Go back"
          onClick={() => navigate(-1)}
          className="w-10 h-10 rounded-[var(--radius-full)] flex items-center justify-center hover:opacity-80 active:scale-95 transition-all"
          style={{ background: "var(--color-bg-elevated)", color: "var(--color-text-secondary)" }}
        >
          <ChevronLeft className="w-5 h-5" />
        </button>
        <div className="text-sm font-semibold font-display" style={s.text}>Help &amp; Support</div>
      </div>

      <div className="flex-1 px-4 py-5 max-w-lg mx-auto w-full">
        <div className="text-xs font-medium uppercase tracking-wider mb-2 px-1 font-body" style={s.tertiary}>Frequently Asked Questions</div>
        <div className="rounded-[var(--radius-xl)] overflow-hidden mb-8" style={{ ...s.surface, boxShadow: "var(--shadow-card)" }}>
          {FAQS.map((item, i) => (
            <div key={item.q} style={{ borderBottom: i < FAQS.length - 1 ? "1px solid var(--color-hairline)" : undefined }}>
              <button
                className="w-full flex items-center justify-between gap-3 px-4 py-3.5 text-left"
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                aria-expanded={openFaq === i}
              >
                <span className="text-sm font-medium font-body" style={s.text}>{item.q}</span>
                <ChevronDown
                  className="w-4 h-4 shrink-0 transition-transform"
                  style={{ ...s.tertiary, transform: openFaq === i ? "rotate(180deg)" : undefined }}
                />
              </button>
              {openFaq === i && (
                <p className="px-4 pb-4 text-sm font-body leading-relaxed" style={s.secondary}>{item.a}</p>
              )}
            </div>
          ))}
        </div>

        <div className="text-xs font-medium uppercase tracking-wider mb-2 px-1 font-body" style={s.tertiary}>Contact Support</div>
        <form onSubmit={handleSubmit} className="rounded-[var(--radius-xl)] p-4 mb-8 space-y-3" style={{ ...s.surface, boxShadow: "var(--shadow-card)" }}>
          <Input placeholder="Subject" value={subject} onChange={(e) => setSubject(e.target.value)} required />
          <textarea
            placeholder="Describe your issue…"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            required
            rows={4}
            className="w-full rounded-[var(--radius-lg)] border px-3 py-2.5 font-body text-sm resize-none"
            style={{ ...s.surface, color: "var(--color-text-primary)" }}
          />
          <Button type="submit" className="w-full" disabled={submitting || !subject.trim() || !message.trim()}>
            {submitting ? "Sending…" : submitted ? "Sent!" : "Submit Request"}
          </Button>
        </form>

        <div className="text-xs font-medium uppercase tracking-wider mb-2 px-1 font-body" style={s.tertiary}>Your Requests</div>
        {tickets.length === 0 ? (
          <div className="flex flex-col items-center text-center py-10">
            <LifeBuoy className="w-8 h-8 mb-3" style={s.tertiary} />
            <p className="text-sm font-body" style={s.secondary}>No requests submitted yet.</p>
          </div>
        ) : (
          <div className="rounded-[var(--radius-xl)] overflow-hidden" style={{ ...s.surface, boxShadow: "var(--shadow-card)" }}>
            {tickets.map((ticket, i) => (
              <div
                key={ticket.id}
                className="px-4 py-3.5"
                style={{ borderBottom: i < tickets.length - 1 ? "1px solid var(--color-hairline)" : undefined }}
              >
                <div className="flex items-center justify-between gap-2 mb-1">
                  <span className="text-sm font-semibold font-body truncate" style={s.text}>{ticket.subject}</span>
                  <Badge tone={TICKET_STATUS_TONE[ticket.status]}>{ticket.status.replace("_", " ")}</Badge>
                </div>
                <div className="text-xs font-body" style={s.tertiary}>{formatRelativeTime(ticket.createdAt)}</div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
